### PR TITLE
Update for Akeneo 5

### PR DESCRIPTION
**Pull request by flagbird**

### CODE REVIEW

**Comment by flagbird** [comment]
`build (7.3)` and `frontend (7.3)` can be ignored in the CI. Those are artifacts from the previous TableAttribute version where PHP 7.3 was in use.

**Comment by nervusdm** [comment]
Can't wait for the 5.0

**Comment by flagbird** [comment]
We are currently evaluating if we modernize our frontend now with the Akeneo 5 update or on a later major release of this bundle.

**Review by joshmuente — APPROVED** [review]

**Review by plel — APPROVED** [review]
Code looks fine. Other tests did not show up the strange behaviour.

**Comment by flagbird** [comment]
I got no green light for handling the legacy of this project and adapting it to a more modern and maintainable approach for Akeneo 5. Maybe next time.

**Comment by nervusdm** [comment]
Cant make it working. I can add TableAttribute, but there is no column option.

Capture d’écran 2021-06-01 à 18 01 14

**Pull request merged**
