### PR TITLE
Add homogenization for translations

### PR DESCRIPTION
**Pull request by AngelVazquezArroyo**
- Custom translation ids instead of Akeneo's were inserted.
- Homogenization of own translations.

### CODE REVIEW

**Comment by AngelVazquezArroyo** [comment]
@flagbird The naming `*.attribute_table.*` was already changed to `*.table_attribute.*`

**Comment by AngelVazquezArroyo** [comment]
> Please change the naming `*.attribute_table.*` to `*.table_attribute.*`. Otherwise this looks fine to me.

@flagbird The naming `*.attribute_table.*` was already changed to `*.table_attribute.*`

**Comment by flagbird** [comment]
Please change the base branch to 2.x.

**Comment by amansilla** [comment]
> Please change the base branch to 2.x.

Done and conflicts were solved.

**Comment by flagbird** [comment]
I'll concentrate my review on the test of the translations only.

**Comment by flagbird** [comment]
@AngelVazquezArroyo In the german translation is still an english word "Key". Is this by decision or is this a missed translation?

**Comment by amansilla** [comment]
> @AngelVazquezArroyo In the german translation is still an english word "Key". Is this by decision or is this a missed translation?

@flagbird the german translation is "Key" since the beginning of this bundle, so is not a missing translation. Anyway we may change it if you've a better alternative, since I'm not german native speaker.

**Pull request merged**
